[sl] ci: fix issues related to `yarn codegen` in CI
Summary:

Currently our CI is failing due to various issues related to the `verify-addons-folder.py` script.

This commit fixes an issue related to `yarn codegen` that made the aforementioned script fail.

Test plan:

## Before

Ran `./verify-addons-folder.py`, and failed with

```
RuntimeError: command failed: yarn codegen
```

Also ran `yarn codegen` in the reviewstack directory, and failed with various errors.

## After

Ran `./verify-addons-folder.py`, and now failed with `RuntimeError: command failed: yarn build` instead.

Also, `yarn codegen` in the reviewstack directory, and it worked without issues.

ghstack-source-id: cc2a596d382b1d320bccfc6878f3399d918e8546
Pull Request resolved: https://github.com/facebook/sapling/pull/502